
agent_name: "AriaMasterAgent"
agent_description: "Central coordination system for managing and orchestrating multiple specialized agents"
agent_type: "coordination"
version: "1.0.0"

capabilities:
  - "agent_coordination"
  - "task_routing" 
  - "workflow_orchestration"
  - "multi_agent_management"
  - "performance_monitoring"
  - "inter_agent_communication"

configuration:
  max_registered_agents: 50
  max_active_workflows: 20
  task_queue_size: 100
  health_check_interval: 30
  coordination_history_size: 1000

dependencies:
  - "base_aria_agent"
  - "logger"

resources:
  memory_usage: "medium"
  cpu_usage: "medium" 
  priority: "high"
