name: "AriaDistortionAgent"
description: "Advanced cognitive distortion detection and correction agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "analysis"
  category: "cognitive_correction"
  priority: "medium"
  
  capabilities:
    - "distortion_detection"
    - "correction_suggestions"
    - "pattern_recognition"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_distortion_analysis"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["distortion", "correction", "patterns"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "distortion"
    - "thinking"
    - "اعوجاج"
    - "تفکر"
    - "شناختی"
    - "اصلاح"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45

openai:
  model: "gpt-4o"
  max_tokens: 600
  temperature: 0.3

distortion_types:
  - "All-or-Nothing Thinking"
  - "Overgeneralization"
  - "Mental Filter"
  - "Disqualifying the Positive"
  - "Jumping to Conclusions"
  - "Magnification or Minimization"
  - "Emotional Reasoning"
  - "Should Statements"
  - "Labeling"
  - "Personalization"

database:
  table_name: "cognitive_distortion_logs"
  fields:
    - "id"
    - "timestamp"
    - "input_text"
    - "distortion_type"
    - "severity_score"
    - "correction_suggestion"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]