name: "AriaGoalAgent"
description: "Advanced goal and intent detection agent with hybrid analysis"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "analysis"
  category: "goal_detection"
  priority: "high"
  
  capabilities:
    - "goal_inference"
    - "intent_detection"
    - "pattern_recognition"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_analysis"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["goals", "intents", "patterns"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "goal"
    - "intent"
    - "purpose"
    - "هدف"
    - "قصد"
    - "منظور"
    - "آرزو"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45

openai:
  model: "gpt-4o"
  max_tokens: 500
  temperature: 0.3

intent_categories:
  - "action/initiation"
  - "decision/choice"
  - "concern/worry"
  - "motivation/energy"
  - "confusion/help"
  - "planning/organization"
  - "learning/knowledge"
  - "health/wellness"
  - "relationship/social"
  - "career/work"
  - "general/other"

confidence_levels:
  - "high"
  - "medium"
  - "low"

database:
  table_name: "goal_inferences"
  fields:
    - "id"
    - "user_id"
    - "input_text"
    - "goal"
    - "intent_category"
    - "confidence"
    - "detected_by"
    - "context_data"
    - "analysis_details"
    - "created_at"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]