name: "AriaBiasAgent"
description: "Advanced cognitive bias detection and reflection agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "analysis"
  category: "cognitive_bias"
  priority: "medium"
  
  capabilities:
    - "bias_detection"
    - "reflection_suggestions"
    - "pattern_recognition"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_bias_analysis"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["bias", "reflection", "patterns"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "bias"
    - "cognitive"
    - "سوگیری"
    - "تعصب"
    - "شناختی"
    - "تأمل"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45

openai:
  model: "gpt-4o"
  max_tokens: 600
  temperature: 0.3

bias_types:
  - "Confirmation Bias"
  - "Availability Bias"
  - "Overconfidence"
  - "Anchoring"
  - "Sunk Cost Fallacy"
  - "Negativity Bias"
  - "Framing Effect"

database:
  table_name: "bias_logs"
  fields:
    - "id"
    - "timestamp"
    - "input_text"
    - "bias_type"
    - "severity_score"
    - "suggestion"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]