
name: "AriaUtilityAgent"
description: "Handles utility and helper tasks with comprehensive data processing capabilities"
version: "1.0.0"
author: "SuperAGI"

capabilities:
  - text_processing
  - data_formatting
  - string_manipulation
  - list_operations
  - dictionary_operations
  - file_operations
  - json_processing
  - utility_functions

parameters:
  max_text_length: 10000
  default_operation: "basic"
  output_format: "json"

dependencies:
  - base_aria_agent

task_types:
  - text_processing
  - data_formatting
  - json_processing
  - list_operations
  - dictionary_operations

input_types:
  - text
  - json
  - list
  - dictionary
  - any

output_formats:
  - processed_data
  - formatted_output
  - operation_result
