
agent_type: "AriaUtilityAgent"
name: "Aria Utility Agent"
description: "Handles utility and system helper tasks for AriaRobot"
capabilities:
  - utility
  - helper
  - system_tasks
  - maintenance
  - diagnostics
default_config:
  max_iterations: 50
  memory_window: 10
  permission_type: "God Mode"
tools:
  - "file"
  - "thinking"
constraints:
  - "Ensure all utility operations are logged"
  - "Validate input parameters before processing"
