name: "AriaRepetitiveAgent"
description: "تحلیلگر الگوهای تکراری و یادگیری از تکرار - Pattern detection agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "learning"
  category: "pattern_analysis"
  priority: "medium"
  
  capabilities:
    - "pattern_detection"
    - "cross_memory_analysis"
    - "repetition_tracking"
    - "warning_system"
    - "postgresql_integration"
    - "persian_patterns"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["patterns", "repetitive", "warning"]
  
  dependencies:
    - "base_agent"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "pattern"
    - "repeat"
    - "الگو"
    - "تکرار"
    - "یادگیری"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 30

pattern_categories:
  - "هدف"
  - "نگرانی"
  - "علاقه"
  - "عادت"
  - "تکرار"

warning_levels:
  critical: 10
  warning: 5
  notable: 3
  normal: 1

database:
  table_name: "repetitive_patterns"
  fields:
    - "id"
    - "user_id"
    - "phrase"
    - "count"
    - "category"
    - "last_occurred_at"
    - "created_at"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: false
  external_apis: []