name: "AriaSecurityAgent"
description: "Advanced cognitive/emotional security threat detection and risk assessment agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "security"
  category: "threat_detection"
  priority: "high"
  
  capabilities:
    - "threat_detection"
    - "risk_assessment"
    - "pattern_recognition"
    - "alert_system"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_security"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["security", "threats", "alerts"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "security"
    - "threat"
    - "امنیت"
    - "تهدید"
    - "خطر"
    - "بررسی"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45

openai:
  model: "gpt-4o"
  max_tokens: 600
  temperature: 0.3

threat_types:
  - "burnout"
  - "emotional_overload"
  - "impulsivity"
  - "cognitive_fatigue"
  - "stress_overload"
  - "decision_paralysis"
  - "anxiety_spiral"
  - "none"

alert_levels:
  - "green"
  - "yellow"
  - "red"

database:
  table_name: "security_checks"
  fields:
    - "id"
    - "input_text"
    - "detected_threat_type"
    - "alert_level"
    - "risk_score"
    - "recommendation"
    - "analysis_data"
    - "created_at"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]