name: "AriaConsensusAgent"
description: "Collaborative decision-making simulation agent with virtual perspectives"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "simulation"
  category: "consensus_building"
  priority: "medium"
  
  capabilities:
    - "consensus_simulation"
    - "virtual_perspectives"
    - "decision_collaboration"
    - "weighted_responses"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_consensus"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["consensus", "decisions", "perspectives"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "consensus"
    - "decision"
    - "group"
    - "اجماع"
    - "تصمیم"
    - "گروهی"
    - "مشورت"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 60

openai:
  model: "gpt-4o"
  max_tokens: 1000
  temperature: 0.4

virtual_agents:
  - "Conservative Analyst"
  - "Creative Thinker"
  - "Practical Problem Solver"
  - "Ethical Evaluator"
  - "Balanced Mediator"

decision_categories:
  - "simple"
  - "complex"
  - "ethical"
  - "strategic"
  - "personal"

database:
  table_name: "consensus_logs"
  fields:
    - "id"
    - "timestamp"
    - "input_text"
    - "virtual_agents"
    - "consensus_result"
    - "final_decision"
    - "confidence_score"
    - "primary_contributor"
    - "decision_data"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]