name: "AriaToolAgent"
description: "Comprehensive tool agent for task processing, analysis, and execution using OpenAI GPT"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

# Agent configuration
agent_config:
  type: "processing"
  category: "task_execution"
  priority: "high"
  
  # Capabilities
  capabilities:
    - "task_detection"
    - "sentiment_analysis"
    - "multi_task_support"
    - "text_processing"
    - "analysis_tools"
    - "openai_integration"
    - "textblob_sentiment"
  
  # Language support
  languages:
    - "persian"
    - "english"
  
  # Memory configuration
  memory:
    short_term_limit: 10
    supports_long_term: false
    memory_types: ["task_processing", "analysis"]
  
  # Dependencies
  dependencies:
    - "base_agent"
    - "openai"
    - "textblob"
    - "logging"
  
  # Routing keywords
  routing_keywords:
    - "analyze"
    - "process"
    - "sentiment"
    - "task"
    - "تحلیل"
    - "پردازش"
    - "احساس"

# Runtime configuration
runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45
  
# OpenAI configuration
openai:
  model: "gpt-4o"
  max_tokens: 800
  temperature: 0.3
  
# Task configuration
task_config:
  supported_tasks:
    - "summarization"
    - "translation"
    - "extraction"
    - "analysis"
    - "improvement"
    - "conversion"
    - "generation"
    - "sentiment_analysis"
  
  confidence_threshold: 0.7
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Integration settings
integration:
  database_required: false
  openai_required: true
  external_apis: ["openai"]