name: "AriaConceptualAgent"
description: "تحلیلگر مفاهیم و ذخیره‌ساز وقایع - AI-powered conceptual analysis agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

# Agent configuration
agent_config:
  type: "analysis"
  category: "conceptual_analysis"
  priority: "medium"
  
  # Capabilities
  capabilities:
    - "concept_extraction"
    - "sentiment_analysis"
    - "category_classification"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_concepts"
  
  # Language support
  languages:
    - "persian"
    - "english"
  
  # Memory configuration
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["conceptual", "categorical", "sentiment"]
  
  # Dependencies
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  # Routing keywords
  routing_keywords:
    - "concept"
    - "analyze"
    - "مفهوم"
    - "تحلیل"
    - "ارزیابی"
    - "احساس"

# Runtime configuration
runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45
  
# OpenAI configuration
openai:
  model: "gpt-4o"
  max_tokens: 500
  temperature: 0.3
  
# Concept categories
concept_categories:
  - "هدف"
  - "ارزش"
  - "تجربه"
  - "اولویت"
  - "ترس"
  - "انگیزه"
  - "نگرانی"
  - "الهام‌بخش"
  
# Sentiment types
sentiment_types:
  - "مثبت"
  - "منفی"
  - "خنثی"
  
# Database configuration
database:
  table_name: "conceptual_memories"
  fields:
    - "id"
    - "user_id"
    - "raw_text"
    - "concept"
    - "category"
    - "sentiment"
    - "created_at"
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Integration settings
integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]