
name: "AriaSummaryAgent"
description: "Specialized agent for content summarization and analysis"
version: "1.0.0"
author: "SuperAGI"

capabilities:
  - text_summarization
  - content_analysis
  - key_point_extraction
  - document_analysis
  - data_aggregation
  - insight_generation
  - report_creation
  - information_distillation

parameters:
  max_summary_length: 500
  default_summary_type: "brief"
  max_key_points: 5
  analysis_depth: "detailed"

dependencies:
  - base_aria_agent

task_types:
  - text_summary
  - data_summary
  - key_points
  - analysis
  - report

input_types:
  - text
  - json
  - dictionary
  - list

output_formats:
  - summary
  - analysis_report
  - key_points_list
  - statistics
