name: "AriaRewardAgent"
description: "Advanced positive progress detection and motivational feedback agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "motivation"
  category: "reward_system"
  priority: "medium"
  
  capabilities:
    - "progress_detection"
    - "motivational_feedback"
    - "reward_triggering"
    - "pattern_recognition"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_rewards"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["rewards", "progress", "motivation"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "reward"
    - "progress"
    - "پاداش"
    - "پیشرفت"
    - "انگیزه"
    - "موفقیت"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 30

openai:
  model: "gpt-4o"
  max_tokens: 400
  temperature: 0.5

trigger_types:
  - "emotional_recovery"
  - "goal_alignment"
  - "security_improvement"
  - "stress_reduction"
  - "positive_mindset"
  - "breakthrough"
  - "consistency"

database:
  table_name: "reward_logs"
  fields:
    - "id"
    - "timestamp"
    - "trigger_type"
    - "reward_message"
    - "emoji"
    - "confidence"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]