name: "AriaMasterAgent"
description: "Central coordinator for managing and routing messages between AI agents"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

# Agent configuration
agent_config:
  type: "coordinator"
  category: "system"
  priority: "high"
  
  # Capabilities
  capabilities:
    - "message_routing"
    - "agent_coordination"
    - "system_orchestration"
    - "persian_language_support"
    - "multi_agent_management"
  
  # Language support
  languages:
    - "persian"
    - "english"
  
  # Memory configuration
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["system", "routing", "agent_status"]
  
  # Dependencies
  dependencies:
    - "base_agent"
    - "database"
    - "logging"
  
  # Routing keywords
  routing_keywords:
    - "status"
    - "system"
    - "help"
    - "route"
    - "coordinate"

# Runtime configuration
runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 30
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Integration settings
integration:
  database_required: true
  openai_required: false
  external_apis: []