name: "AriaEthicalAgent"
description: "Advanced ethical reasoning and decision analysis agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "analysis"
  category: "ethical_reasoning"
  priority: "high"
  
  capabilities:
    - "ethical_analysis"
    - "moral_reasoning"
    - "risk_assessment"
    - "framework_application"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_ethics"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["ethical", "moral", "reasoning"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "ethical"
    - "moral"
    - "اخلاقی"
    - "معنوی"
    - "اصول"
    - "ارزش"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 60

openai:
  model: "gpt-4o"
  max_tokens: 800
  temperature: 0.3

ethical_frameworks:
  - "consequentialism"
  - "deontological"
  - "virtue_ethics"
  - "care_ethics"
  - "justice_theory"

risk_levels:
  - "low"
  - "medium"
  - "high"
  - "critical"

database:
  table_name: "ethical_logs"
  fields:
    - "id"
    - "timestamp"
    - "input_text"
    - "ethical_framework"
    - "risk_level"
    - "recommendation"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]