name: "AriaSummaryAgent"
description: "AI agent for comprehensive text summarization with database storage"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

# Agent configuration
agent_config:
  type: "summarization"
  category: "text_processing"
  priority: "medium"
  
  # Capabilities
  capabilities:
    - "text_summarization"
    - "database_storage"
    - "compression_ratio_calculation"
    - "openai_integration"
    - "postgresql_integration"
  
  # Language support
  languages:
    - "persian"
    - "english"
  
  # Memory configuration
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["summarization", "database"]
  
  # Dependencies
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  # Routing keywords
  routing_keywords:
    - "summarize"
    - "خلاصه"
    - "summary"
    - "compress"
    - "شرح"

# Runtime configuration
runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 60
  
# OpenAI configuration
openai:
  model: "gpt-4o"
  max_tokens: 1000
  temperature: 0.3
  
# Database configuration
database:
  table_name: "summaries"
  fields:
    - "id"
    - "original_text"
    - "summary"
    - "created_at"
  
# Processing configuration
processing:
  min_text_length: 50
  max_text_length: 10000
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Integration settings
integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]