name: "AriaAdvancedMemoryAgent"
description: "Centralized memory management system with intelligent classification"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "management"
  category: "advanced_memory"
  priority: "high"
  
  capabilities:
    - "memory_classification"
    - "cross_agent_communication"
    - "importance_scoring"
    - "context_analysis"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_memory"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["short_term", "long_term", "mission_specific", "reflective"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "memory"
    - "advanced"
    - "حافظه"
    - "پیشرفته"
    - "مدیریت"
    - "ذخیره"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45

openai:
  model: "gpt-4o"
  max_tokens: 600
  temperature: 0.3

memory_types:
  - "short_term"
  - "long_term"
  - "mission_specific"
  - "reflective"

importance_scale:
  min: 1
  max: 10
  threshold: 7

database:
  tables:
    - "memory_entries"
    - "memory_summaries"
  
  memory_entries_fields:
    - "id"
    - "user_id"
    - "agent_name"
    - "memory_type"
    - "mission_id"
    - "content"
    - "metadata"
    - "importance_score"
    - "access_count"
    - "created_at"
    - "updated_at"
    - "expires_at"
    - "is_active"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]