name: "AriaEmotionAgent"
description: "Advanced emotion detection and regulation agent with therapeutic suggestions"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "analysis"
  category: "emotion_regulation"
  priority: "high"
  
  capabilities:
    - "emotion_detection"
    - "intensity_analysis"
    - "regulation_suggestions"
    - "pattern_recognition"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_emotions"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["emotions", "patterns", "regulation"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "emotion"
    - "feeling"
    - "احساس"
    - "عاطفه"
    - "حال"
    - "خلق"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 45

openai:
  model: "gpt-4o"
  max_tokens: 600
  temperature: 0.3

emotion_types:
  - "خشم"
  - "استیصال"
  - "اضطراب"
  - "هیجان"
  - "بی‌انگیزگی"
  - "رضایت"
  - "خوشحالی"
  - "غم"
  - "سردرگمی"
  - "استرس"
  - "ترس"
  - "امید"
  - "خنثی"

intensity_levels:
  - "خفیف"
  - "متوسط"
  - "شدید"

database:
  table_name: "emotional_states"
  fields:
    - "id"
    - "user_id"
    - "input_text"
    - "emotion_type"
    - "intensity"
    - "suggestion"
    - "confidence"
    - "context_data"
    - "created_at"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]