name: "AriaKnowledgeAgent"
description: "سازنده گراف دانش و تحلیلگر روابط مفهومی - Knowledge graph construction agent"
version: "1.0.0"
author: "AriaRobot Team"
license: "MIT"

agent_config:
  type: "analysis"
  category: "knowledge_management"
  priority: "medium"
  
  capabilities:
    - "concept_extraction"
    - "relationship_mapping"
    - "knowledge_graph_construction"
    - "openai_integration"
    - "postgresql_integration"
    - "persian_concepts"
  
  languages:
    - "persian"
    - "english"
  
  memory:
    short_term_limit: 10
    supports_long_term: true
    memory_types: ["knowledge", "concepts", "relationships"]
  
  dependencies:
    - "base_agent"
    - "openai"
    - "postgresql"
    - "sqlalchemy"
    - "logging"
  
  routing_keywords:
    - "knowledge"
    - "graph"
    - "concept"
    - "دانش"
    - "گراف"
    - "مفهوم"
    - "رابطه"

runtime:
  auto_start: true
  restart_on_failure: true
  timeout: 60

openai:
  model: "gpt-4o"
  max_tokens: 800
  temperature: 0.3

relationship_types:
  - "علت_معلول"
  - "شامل"
  - "مرتبط"
  - "مشابه"
  - "متضاد"
  - "زمانی"
  - "مکانی"

concept_types:
  - "شخص"
  - "مکان"
  - "شیء"
  - "ایده"
  - "فرآیند"
  - "هدف"
  - "مشکل"
  - "راه‌حل"

database:
  table_name: "knowledge_graph"
  fields:
    - "id"
    - "user_id"
    - "source_text"
    - "concepts"
    - "relationships"
    - "graph_data"
    - "created_at"
    - "updated_at"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

integration:
  database_required: true
  openai_required: true
  external_apis: ["openai"]